
FIND_PATH( PHYSX_INCLUDE_DIR physx/PxPhysicsAPI.h
	/usr/include
	/usr/local/include
	/opt/local/include
	${CMAKE_SOURCE_DIR}/includes
)
FIND_LIBRARY( PHYSX_LIBRARY_PhysX PhysX_64
	/usr/lib64
	/usr/lib
	/usr/local/lib
	/opt/local/lib
	${CMAKE_SOURCE_DIR}/lib
)

IF(PHYSX_INCLUDE_DIR AND PHYSX_LIBRARY_PhysX )
	SET( PHYSX_FOUND TRUE )
	SET( PHYSX_LIBRARY_PhysX ${PHYSX_LIBRARY} )
ENDIF(PHYSX_INCLUDE_DIR AND PHYSX_LIBRARY_PhysX)
IF(PHYSX_FOUND)
	IF(NOT PHYSX_FIND_QUIETLY)
	MESSAGE(STATUS "Found PHYSX: ${PHYSX_LIBRARY}")
	ENDIF(NOT PHYSX_FIND_QUIETLY)
ELSE(PHYSX_FOUND)
	IF(PHYSX_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find lib PHYSX")
	ENDIF(PHYSX_FIND_REQUIRED)
ENDIF(PHYSX_FOUND)
