

SET(_boost_ENV_INCLUDE_DIR "$ENV{BOOST_INCLUDEDIR}")
SET(_boost_ENV_LIB_DIR "$ENV{BOOST_LIBRARYDIR}")

SET(Boost_LIBRARY_DIR "${_boost_ENV_LIB_DIR}")
SET(Boost_INCLUDE_DIRS "${_boost_ENV_INCLUDE_DIR}")
